#!/usr/bin/env node
// Builds js/game.bundle.js by concatenating the game scripts in dependency order
// (core -> data -> sim -> net -> render -> ui). Concatenation (not a bundler) is
// what lets the game load straight from file:// with two <script> tags and no
// bundler — each script is a self-contained IIFE that attaches to window.E.
'use strict';
const fs = require('fs'), path = require('path');
const ROOT = path.join(__dirname, '..');
const ORDER = ['core', 'data', 'sim', 'net', 'render', 'ui'];

function list() {
  const files = [];
  for (const d of ORDER) {
    const dir = path.join(ROOT, 'js', d);
    if (!fs.existsSync(dir)) continue;
    for (const f of fs.readdirSync(dir).sort()) if (f.endsWith('.js')) files.push(`js/${d}/${f}`);
  }
  return files;
}

const files = list();
let out = '/* galactic-conquest bundle — generated by tools/build.cjs, do not edit */\n(function(){\n"use strict";\n';
const parts = [];
for (const f of files) {
  const code = fs.readFileSync(path.join(ROOT, f), 'utf8');
  parts.push(`// ---- ${f} ----\n` + code);
}
out += parts.join('\n');
out += `\nwindow.__GC_READY__ = true;\n})();\n`;
fs.writeFileSync(path.join(ROOT, 'js/game.bundle.js'), out);
console.log(`bundle: ${files.length} scripts -> js/game.bundle.js (${(out.length / 1024).toFixed(0)} KB)`);
